services:
  ai.receipts:
    image: ${DOCKER_REGISTRY-}ai.receipts:${VERSION}
    build:
      context: ./src
      dockerfile: AI.Receipts/Dockerfile
      args:
        - AUTHORS=${AUTHORS}
        - VERSION=${VERSION}
        - TITLE=${TITLE}
        - DESCRIPTION=${DESCRIPTION}
        - BUILD_DATE=${BUILD_DATE}
    ports:
      - 9020:8081
    networks:
      - ai_receipts_network
    depends_on:
      seq:
        condition: service_started
      ollama:
        condition: service_started
      openwebui:
        condition: service_started
    volumes:
      - ai_receipts_logs:/app/logs/ai_receipts/
      - ai_receipts_sqlite:/app/db/
      - ai_receipts_uploads:/app/uploads/
    user: "1654:1654"

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    networks:
      - ai_receipts_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 8080:8080
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ai_receipts_network
    restart: always

  seq:
    image: datalust/seq:latest
    ports:
      - 5341:5341
      - 8081:80
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_FIRSTRUN_ADMINPASSWORD}
    networks:
      - ai_receipts_network
    volumes:
      - ai_receipts_seq_data:/data
    restart: always

networks:
  ai_receipts_network:
    driver: bridge

volumes:
  ai_receipts_sqlite:
  ai_receipts_logs:
  ai_receipts_seq_data:
  ai_receipts_uploads:
  ollama:
  open-webui:
