services:
  AI.Receipts:
    image: ${DOCKER_REGISTRY-}AI.Receipts:${VERSION}
    build:
      context: .
      dockerfile: AI.Receipts/Dockerfile
      args:
        - AUTHORS=${AUTHORS}
        - VERSION=${VERSION}
        - TITLE=${TITLE}
        - DESCRIPTION=${DESCRIPTION}
    ports:
      - 9020:8081
    networks:
      - ai_receipts_network
    depends_on:
      seq:
        condition: service_started
      ollama:
        condition: service_started
    volumes:
      - ai_receipts_logs:/app/logs/ai_receipts/

  sqllite:
    image: alpine/sqlite3@sha256:23ac7965b66fe40c9aaeeebd231230bda79c972a2759a6b9c20e67e668e1a5d7
    working_dir: /apps
    volumes:
      - ai_receipts_sqlite:/apps

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    networks:
      - ai_receipts_network
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 8080:8080
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ai_receipts_network
    restart: always

  seq:
    image: datalust/seq@sha256:3cfad751637b869617ff7fc296495681f5365a8c3046b36ab654a0f5a8ff04e5
    ports:
      - 5341:5341
      - 8081:80
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_FIRSTRUN_ADMINPASSWORD}
    networks:
      - ai_receipts_network
    volumes:
      - ai_receipts_seq_data:/data
    restart: always

networks:
  ai_receipts_network:
    driver: bridge

volumes:
  ai_receipts_sqlite:
  ai_receipts_logs:
  ai_receipts_seq_data:
  ollama:
  open-webui:

